//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ServiceManual.WRAliPay {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AliPayWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AliPayWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PreCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryByOrderNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelPreOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRenewalPriceInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRenewalInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNetConfigInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetNetConfigInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AliPayWebService() {
            this.Url = global::ServiceManual.Properties.Settings.Default.ServiceManual_WRAliPay_AliPayWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PreCreateCompletedEventHandler PreCreateCompleted;
        
        /// <remarks/>
        public event QueryByOrderNoCompletedEventHandler QueryByOrderNoCompleted;
        
        /// <remarks/>
        public event CancelPreOrderCompletedEventHandler CancelPreOrderCompleted;
        
        /// <remarks/>
        public event GetRenewalPriceInfoCompletedEventHandler GetRenewalPriceInfoCompleted;
        
        /// <remarks/>
        public event SetRenewalInfoCompletedEventHandler SetRenewalInfoCompleted;
        
        /// <remarks/>
        public event GetNetConfigInfoCompletedEventHandler GetNetConfigInfoCompleted;
        
        /// <remarks/>
        public event SetNetConfigInfoCompletedEventHandler SetNetConfigInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PreCreate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result PreCreate(string account, string renewalWay) {
            object[] results = this.Invoke("PreCreate", new object[] {
                        account,
                        renewalWay});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void PreCreateAsync(string account, string renewalWay) {
            this.PreCreateAsync(account, renewalWay, null);
        }
        
        /// <remarks/>
        public void PreCreateAsync(string account, string renewalWay, object userState) {
            if ((this.PreCreateOperationCompleted == null)) {
                this.PreCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPreCreateOperationCompleted);
            }
            this.InvokeAsync("PreCreate", new object[] {
                        account,
                        renewalWay}, this.PreCreateOperationCompleted, userState);
        }
        
        private void OnPreCreateOperationCompleted(object arg) {
            if ((this.PreCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PreCreateCompleted(this, new PreCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryByOrderNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result QueryByOrderNo(string account, string orderNo) {
            object[] results = this.Invoke("QueryByOrderNo", new object[] {
                        account,
                        orderNo});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void QueryByOrderNoAsync(string account, string orderNo) {
            this.QueryByOrderNoAsync(account, orderNo, null);
        }
        
        /// <remarks/>
        public void QueryByOrderNoAsync(string account, string orderNo, object userState) {
            if ((this.QueryByOrderNoOperationCompleted == null)) {
                this.QueryByOrderNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryByOrderNoOperationCompleted);
            }
            this.InvokeAsync("QueryByOrderNo", new object[] {
                        account,
                        orderNo}, this.QueryByOrderNoOperationCompleted, userState);
        }
        
        private void OnQueryByOrderNoOperationCompleted(object arg) {
            if ((this.QueryByOrderNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryByOrderNoCompleted(this, new QueryByOrderNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelPreOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result CancelPreOrder(string account, string orderNo) {
            object[] results = this.Invoke("CancelPreOrder", new object[] {
                        account,
                        orderNo});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void CancelPreOrderAsync(string account, string orderNo) {
            this.CancelPreOrderAsync(account, orderNo, null);
        }
        
        /// <remarks/>
        public void CancelPreOrderAsync(string account, string orderNo, object userState) {
            if ((this.CancelPreOrderOperationCompleted == null)) {
                this.CancelPreOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelPreOrderOperationCompleted);
            }
            this.InvokeAsync("CancelPreOrder", new object[] {
                        account,
                        orderNo}, this.CancelPreOrderOperationCompleted, userState);
        }
        
        private void OnCancelPreOrderOperationCompleted(object arg) {
            if ((this.CancelPreOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelPreOrderCompleted(this, new CancelPreOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRenewalPriceInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetRenewalPriceInfo() {
            object[] results = this.Invoke("GetRenewalPriceInfo", new object[0]);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetRenewalPriceInfoAsync() {
            this.GetRenewalPriceInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetRenewalPriceInfoAsync(object userState) {
            if ((this.GetRenewalPriceInfoOperationCompleted == null)) {
                this.GetRenewalPriceInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRenewalPriceInfoOperationCompleted);
            }
            this.InvokeAsync("GetRenewalPriceInfo", new object[0], this.GetRenewalPriceInfoOperationCompleted, userState);
        }
        
        private void OnGetRenewalPriceInfoOperationCompleted(object arg) {
            if ((this.GetRenewalPriceInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRenewalPriceInfoCompleted(this, new GetRenewalPriceInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetRenewalInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SetRenewalInfo(string priceF, string renewalTimeF, string priceS, string renewalTimeS) {
            object[] results = this.Invoke("SetRenewalInfo", new object[] {
                        priceF,
                        renewalTimeF,
                        priceS,
                        renewalTimeS});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SetRenewalInfoAsync(string priceF, string renewalTimeF, string priceS, string renewalTimeS) {
            this.SetRenewalInfoAsync(priceF, renewalTimeF, priceS, renewalTimeS, null);
        }
        
        /// <remarks/>
        public void SetRenewalInfoAsync(string priceF, string renewalTimeF, string priceS, string renewalTimeS, object userState) {
            if ((this.SetRenewalInfoOperationCompleted == null)) {
                this.SetRenewalInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRenewalInfoOperationCompleted);
            }
            this.InvokeAsync("SetRenewalInfo", new object[] {
                        priceF,
                        renewalTimeF,
                        priceS,
                        renewalTimeS}, this.SetRenewalInfoOperationCompleted, userState);
        }
        
        private void OnSetRenewalInfoOperationCompleted(object arg) {
            if ((this.SetRenewalInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRenewalInfoCompleted(this, new SetRenewalInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNetConfigInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result GetNetConfigInfo() {
            object[] results = this.Invoke("GetNetConfigInfo", new object[0]);
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetNetConfigInfoAsync() {
            this.GetNetConfigInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetNetConfigInfoAsync(object userState) {
            if ((this.GetNetConfigInfoOperationCompleted == null)) {
                this.GetNetConfigInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNetConfigInfoOperationCompleted);
            }
            this.InvokeAsync("GetNetConfigInfo", new object[0], this.GetNetConfigInfoOperationCompleted, userState);
        }
        
        private void OnGetNetConfigInfoOperationCompleted(object arg) {
            if ((this.GetNetConfigInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNetConfigInfoCompleted(this, new GetNetConfigInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetNetConfigInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result SetNetConfigInfo(string josnValue) {
            object[] results = this.Invoke("SetNetConfigInfo", new object[] {
                        josnValue});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void SetNetConfigInfoAsync(string josnValue) {
            this.SetNetConfigInfoAsync(josnValue, null);
        }
        
        /// <remarks/>
        public void SetNetConfigInfoAsync(string josnValue, object userState) {
            if ((this.SetNetConfigInfoOperationCompleted == null)) {
                this.SetNetConfigInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetNetConfigInfoOperationCompleted);
            }
            this.InvokeAsync("SetNetConfigInfo", new object[] {
                        josnValue}, this.SetNetConfigInfoOperationCompleted, userState);
        }
        
        private void OnSetNetConfigInfoOperationCompleted(object arg) {
            if ((this.SetNetConfigInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetNetConfigInfoCompleted(this, new SetNetConfigInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private string descriptionField;
        
        private string extDataField;
        
        private string failDescriptionField;
        
        private int failNumField;
        
        private bool isOKField;
        
        private int numField;
        
        private int stateCodeIDField;
        
        private string succeedDescriptionField;
        
        private int succeedNumField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ExtData {
            get {
                return this.extDataField;
            }
            set {
                this.extDataField = value;
            }
        }
        
        /// <remarks/>
        public string FailDescription {
            get {
                return this.failDescriptionField;
            }
            set {
                this.failDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int FailNum {
            get {
                return this.failNumField;
            }
            set {
                this.failNumField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOK {
            get {
                return this.isOKField;
            }
            set {
                this.isOKField = value;
            }
        }
        
        /// <remarks/>
        public int Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        public int StateCodeID {
            get {
                return this.stateCodeIDField;
            }
            set {
                this.stateCodeIDField = value;
            }
        }
        
        /// <remarks/>
        public string SucceedDescription {
            get {
                return this.succeedDescriptionField;
            }
            set {
                this.succeedDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int SucceedNum {
            get {
                return this.succeedNumField;
            }
            set {
                this.succeedNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PreCreateCompletedEventHandler(object sender, PreCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PreCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PreCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void QueryByOrderNoCompletedEventHandler(object sender, QueryByOrderNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryByOrderNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryByOrderNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CancelPreOrderCompletedEventHandler(object sender, CancelPreOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelPreOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelPreOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetRenewalPriceInfoCompletedEventHandler(object sender, GetRenewalPriceInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRenewalPriceInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRenewalPriceInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetRenewalInfoCompletedEventHandler(object sender, SetRenewalInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRenewalInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetRenewalInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetNetConfigInfoCompletedEventHandler(object sender, GetNetConfigInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNetConfigInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNetConfigInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SetNetConfigInfoCompletedEventHandler(object sender, SetNetConfigInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetNetConfigInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetNetConfigInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591